Update xhr-basic.html
mdn/learning-area pull request #320
Opened 2020-12-15 19:15 UTC by mrxdkox

Change 'var' to 'const, let', so it relate to ajax-finish.html

2020-12-17 11:18 UTC, chrisdavidmills requested changes
Hi @mrxdkox ! Thanks for fixing this up.

I just had one comment for you to address, but apart from that we are good to go.

2020-12-17 11:18 UTC, chrisdavidmills commented on javascript/apis/fetching-data/xhr-basic.html
> +         verse = verseChoose.value;
This needs a `const`

2020-12-18 19:42 UTC, mrxdkox commented on javascript/apis/fetching-data/xhr-basic.html
> +         verse = verseChoose.value;
Got it, thx.

2020-12-18 23:04 UTC, chrisdavidmills approved these changes
Great, thanks!

2020-12-18 23:05 UTC, merged