fix(readonly-confirmation): fix read-only prefix error
mdn/learning-area pull request #506
Opened 2022-06-12 06:36 UTC by Tongky-HGU

#### Summary

- fix CSS error in `:read-only` example

#### Motivation

- `:read-only` CSS is not working properly in Chorme.
- `-moz-` prefix won't work with Chome browser.
- Chome ignores whole CSS block with invalid prefix.

*As-Is*
<img width="542" alt="image" src="https://user-images.githubusercontent.com/73219421/173220104-f2087f86-74f2-4fd5-b6db-40822c16b4a4.png">
*To-Be*
<img width="532" alt="image" src="https://user-images.githubusercontent.com/73219421/173220087-4c6fec46-0c80-4450-b07d-a14b1d43117b.png">

#### Supporting details

> A selector always goes together with a declaration block.
> When a user agent cannot parse the selector (i.e., it is not valid CSS 2.1),
> it must ignore the selector and the following declaration block (if any) as well.
> &mdash; [4.1.7 Rule sets, declaration blocks, and selectors](<https://www.w3.org/TR/CSS21/syndata.html#rule-sets:~:text=A%20selector%20always%20goes%20together%20with%20a%20declaration%20block.%20When%20a%20user%20agent%20cannot%20parse%20the%20selector%20(i.e.%2C%20it%20is%20not%20valid%20CSS%C2%A02.1)%2C%20it%20must%20ignore%20the%20selector%20and%20the%20following%20declaration%20block%20(if%20any)%20as%20well.>)

- [autoprefixer](https://autoprefixer.github.io/) result
```css
/* input */
input:read-only,
textarea:read-only {
  border: 0;
  box-shadow: none;
  background-color: white;
}
```

```css
/* output */
input:-moz-read-only, textarea:-moz-read-only {
  border: 0;
  box-shadow: none;
  background-color: white;
}
input:read-only,
textarea:read-only {
  border: 0;
  -webkit-box-shadow: none;
          box-shadow: none;
  background-color: white;
}
```

2022-06-12 06:42 UTC, teoli2003 commented
>     * `:read-only` CSS is not working properly in Chrome.

Can you elaborate on this? According to the browser compatibility data `:read-only` is supported since Chrome 1.

Also, Firefox supports `:read-only` without prefix for 2 years. 

I would prefer to remove all prefixes in this case.

2022-06-12 06:44 UTC, teoli2003 requested changes

2022-06-12 06:44 UTC, teoli2003 commented on html/forms/pseudo-classes/readonly-confirmation.html
> +                box-shadow: none;
Am I wrong in saying no browser support unprefixed `box-shadow`?

2022-06-12 06:44 UTC, teoli2003 commented on html/forms/pseudo-classes/readonly-confirmation.html
> +                box-shadow: inset 1px 1px 3px #ccc;
Same here

2022-06-12 06:44 UTC, teoli2003 commented
@teoli2003, @wbamberg What is the policy with added an unprefixed CSS property when no browser supports it unprefixed (and all, including Gecko, with the `-webkit` prefix?

2022-06-20 01:51 UTC, Tongky-HGU commented
I think my PR is misleading. `:-moz-read-only` blocks whole css block include `:read-only`, so example is not working properly in Chorme.

I believe that all the above questions are discussed here. -> https://github.com/mdn/content/pull/17200

2022-08-09 05:44 UTC, teoli2003 approved these changes

2022-08-09 05:44 UTC, merged

2024-01-12 07:14 UTC, vlakoff commented
I've just added a comment on the sibling ticket: https://github.com/mdn/content/pull/17200#issuecomment-1888547101.