Button text change
mdn/learning-area pull request #770
Opened 2024-10-08 20:42 UTC by Chaya90

2024-10-14 08:39 UTC, zeenox-stack commented on javascript/building-blocks/tasks/events/events1-download.html
> +    const clickButton = function (newText) => {
use the normal function rather than using the arrow syntax here.

2024-10-14 08:44 UTC, zeenox-stack commented on javascript/building-blocks/tasks/events/events1-download.html
You also have to call the clickButton variable with function with the newText as its argument to make sure it is working properly. Something like this:

clickButton(newText);

2024-10-14 08:45 UTC, zeenox-stack requested changes
The comments should help you solve the problems

2024-10-18 14:47 UTC, pepelsbey commented
Hey! This is a sample file for anyone to use as a [starting point](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Events#events_1) in testing their skills. Feel free to practice in your fork :)

2024-10-18 14:47 UTC, closed without merging